const mongoose = require("mongoose");

const musclesSchema = new mongoose.Schema({
  name: {
    type: String,
    enum: [
      "Trapezius",
      "Front Deltoideus",
      "Middle Deltoideus",
      "Rear Deltoideus",
      "Upper Chest",
      "Middle Chest",
      "Upper Back",
      "Latissimus",
      "Lower Back",
      "Tricep",
      "Bicep",
      "Abdominals",
      "Side Abs",
      "Forearm",
      "Gluteus",
      "Quadriceps",
      "Adductor",
      "Abductor",
      "Hamstrings",
      "Tibialis",
      "Calfs",
    ],
    required: true,
  },
  latinName: {
    type: String,
    enum: [
      "Trapezius",
      "Anterior Deltoideus",
      "Lateral Deltoideus",
      "Posterior Deltoideus",
      "Pectoralis Minor",
      "Pectoralis Major",
      "Upper Back",
      "Latissimus Dorsi",
      "Lower Back",
      "Triceps Brachii",
      "Biceps Brachii",
      "Antebrachium",
      "Rectus Abdominis",
      "Abdominal external oblique",
      "Gluteus maximus",
      "Quadriceps",
      "Adductors",
      "Abductors",
      "Biceps Femoris",
      "Gastrocnemius",
      "Tibialis Anterior",
    ],
    required: true,
  },
  bodyPart: {
    type: String,
    enum: ["Upper Body", "Lower Body"],
    required: true,
  },
  muscleGroup: {
    type: String,
    enum: ["Chest", "Back", "Shoulders", "Arms", "Legs", "Abdomen", "Glutes"],
    required: true,
  },
  description: { type: String, required: true },
  movements: { type: String, required: true },
  exercises: { type: Array, required: true },
  equipment: { type: Array, required: true },
});

module.exports = mongoose.model("Muscles", musclesSchema);
